apiVersion: v1
kind: ConfigMap
metadata:
  name: auth
data:
  authorized_keys: "ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAACAQDTn1K0UQ0UQMnilIvlEiHwkTEXec9Bwawx20wBfjDEE5DVxLp9GpaqQr4V0le5QszQnFbtf9LWbXqMCg5Buf91gcxaTqDDQtAJK4A6m7rFK8dnfhIVasszmSQ/sM5ijG+wZbI/Zizi06s8qd4FhoTXOhgNoLlf4/R4j2ZmSt9Gf5MpNBSiQnLbhMkcYP7ImqvzrWEOBMY+aLgai0qZueHm//DRqd2pTe2YUs+Vm1hTH+LWU7T0BlBM2tDqpkYZxk+iHWQsy3HbDv5AwO8HLE4M6Of7P+GnNHHF0atuRBiimHCfNn841DP0RMPMWbkfibLOy3MYZhs3H0mlKrbPkGy6knczyq1/fQl4I7cCqdIMb0JixD83EaW30BNSGY1a5hftJrJpwz3rLybBi0+/d27/KM8LCIvTc0vt6Oyrugoq6aqsy4FZtGjzqF5YVSrfmwJhQTYyBxyByUhu9CMhGWNl2xqF/IN2k7MLxYv467iNvE5M3BWACts/p/R5uNxj5clhaozgqjihI7pIbpddEmSnU1u9R3uI3cSRAzRoMuZv6/skyaXzsqcYyplM1Y0uoVwWMWgbmd5mOXJyC6BvgdKoVxcIiEsanafdQc/Yt96fG18+GW6kE990uYgNb5cOsroOkYEfnPVYgOYJBdyidV7H8E6+UZ3vMphfKuVWVeUPvQ== emil.ohgren@dgc.se"
